[package]
name = "weather_reporter"
version = "0.1.0"
edition = "2021"

[dependencies]
blocking = "1.6.1"
chrono = "0.4.39"
libmath = "0.2.1"
tokio = { version = "1.15", features = ["full"] }
reqwest = { version = "0.11.22", features = ["json"] }
serde_json = "1.0.133"